# Generated by Django 5.1.4 on 2024-12-20 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["created"]},
        ),
    ]
