# Generated by Django 5.1.4 on 2024-12-17 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_review_owner_alter_review_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
