# Generated by Django 5.1.4 on 2024-12-17 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_review_created"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-vote_ratio", "-vote_total", "title"]},
        ),
    ]
